project:
  type: website

website:
  title: "Physics Lecture Notes"
  navbar:
    right:
      - icon: github
        href: https://github.com/vitenti-physics/vitenti-physics.github.io
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-R4D0BX334F"
    anonymize-ip: true  
  sidebar:
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Undergraduate"
          contents:
            - section: "Introduction to Physics (portuguese)"
              contents:
                - text: "Overview"
                  href: courses/introduction-to-physics/index.qmd
                - text: "Physics and Mathematics"
                  href: courses/introduction-to-physics/physics-math.qmd
                - text: "Determinism and Statistics"
                  href: courses/introduction-to-physics/determinism-statistics.qmd
                - text: "Introduction to Statistical Mechanics"
                  href: courses/introduction-to-physics/intro-stat-mechanics.qmd
                - text: "Introduction to Heisenberg Uncertainty Principle"
                  href: courses/introduction-to-physics/heisenberg-uncertainty.qmd
                - text: "Selected Exercises"
                  href: courses/introduction-to-physics/selected-exercises.qmd
            - section: "Vector Calculus"
              contents:
                - text: "Overview"
                  href: courses/vector-calculus/index.qmd
                - text: "Vector Spaces Products and Maps"
                  href: courses/vector-calculus/vector-spaces.qmd
            - section: "Mathematical Physics"
              contents:
                - text: "Overview"
                  href: courses/mathematical-physics/index.qmd
                - text: "Dirac Delta"
                  href: courses/mathematical-physics/delta-dirac-green.qmd
                - text: "Green Functions"
                  href: courses/mathematical-physics/green-functions-nd.qmd
                - text: "Propagators and Symplectic Structures"
                  href: courses/mathematical-physics/propagators-symplectic.qmd
                - text: "Propagators: Complete Solutions"
                  href: courses/mathematical-physics/propagators-cont.qmd
                - text: "Propagators in Field Theory"
                  href: courses/mathematical-physics/propagators-fields.qmd
                - text: "Scalar Fields"
                  href: courses/mathematical-physics/scalar-field.qmd
                - text: "Scalar Fields: Propagators and Vacuum"
                  href: courses/mathematical-physics/scalar-propagators.qmd
            - section: "Special Relativity"
              contents:
                - text: "Overview"
                  href: courses/special-relativity/index.qmd
                - text: "Galilean Relativity"
                  href: courses/special-relativity/galilean-relativity.qmd
                - text: "Spacetime Algebra"
                  href: courses/special-relativity/spacetime-algebra.qmd
        - section: "Graduate"
          contents:
            - section: "Electrodynamics"
              contents:
                - text: "Overview"
                  href: courses/electrodynamics/index.qmd
                - text: "Conventions and Notation"
                  href: courses/electrodynamics/conventions.qmd
                - text: "Geometry Review for Electrodynamics"
                  href: courses/electrodynamics/geometry-review.qmd
                - text: "Calculus on Minkowski Spacetime"
                  href: courses/electrodynamics/calculus-on-minkowski-spacetime.qmd
                - text: "Maxwell Equations in Covariant Form"
                  href: courses/electrodynamics/maxwell-equations-forms.qmd
                - text: "Accelerated Observers and Born Rigidity"
                  href: courses/electrodynamics/accel.qmd
                - text: "Energy of the Electromagnetic Field"
                  href: courses/electrodynamics/em-energy.qmd
                - text: "Radiation from a Moving Charge"
                  href: courses/electrodynamics/moving-charge-radiation.qmd
                - text: "Thomson Scattering"
                  href: courses/electrodynamics/thomson-scattering.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly      
    toc: true
    page-layout: full
    css: style.css
    grid:
      body-width: 1200px
    fig-cap-location: margin
    reference-location: margin
    citation-location: margin
  pdf:
    geometry: margin=2.5cm
    documentclass: article
format-links: [pdf]

authors:
  - Sandro Vitenti
jupyter: python3
license: CC BY-NC-SA 4.0
