project:
  type: website

website:
  title: "Physics Lecture Notes"
  navbar:
    right:
      - icon: github
        href: https://vitenti-physics.github.io/
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-R4D0BX334F"
    anonymize-ip: true  
  sidebar:
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Undergraduate"
          contents:
            - section: "Introduction to Physics (portuguese)"
              contents:
                - text: "Overview"
                  href: courses/introduction-to-physics/index.qmd
                - text: "Physics and Mathematics"
                  href: courses/introduction-to-physics/physics-math.qmd
                - text: "Determinism and Statistics"
                  href: courses/introduction-to-physics/determinism-statistics.qmd
                - text: "Introduction to Statistical Mechanics"
                  href: courses/introduction-to-physics/intro-stat-mechanics.qmd
                - text: "Introduction to Heisenberg Uncertainty Principle"
                  href: courses/introduction-to-physics/heisenberg-uncertainty.qmd
                - text: "Selected Exercises"
                  href: courses/introduction-to-physics/selected-exercises.qmd
            - section: "Vector Calculus"
              contents:
                - text: "Overview"
                  href: courses/vector-calculus/index.qmd
                - text: "Vector Spaces Products and Maps"
                  href: courses/vector-calculus/vector-spaces.qmd
            - section: "Mathematical Physics"
              contents:
                - text: "Overview"
                  href: courses/mathematical-physics/index.qmd
                - text: "Dirac Delta"
                  href: courses/mathematical-physics/dirac-delta.qmd
                - text: "Green Functions"
                  href: courses/mathematical-physics/green-functions.qmd
                - text: "Time Dependent Green Functions"
                  href: courses/mathematical-physics/time-dependent-green-functions.qmd
            - section: "Special Relativity"
              contents:
                - text: "Overview"
                  href: courses/special-relativity/index.qmd
                - text: "Galilean Relativity"
                  href: courses/special-relativity/galilean-relativity.qmd
                - text: "Spacetime Algebra"
                  href: courses/special-relativity/spacetime-algebra.qmd
        - section: "Graduate"
          contents:
            - section: "Electrodynamics"
              contents:
                - text: "Overview"
                  href: courses/electrodynamics/index.qmd
                - text: "Geometry Review for Electrodynamics"
                  href: courses/electrodynamics/geometry-review.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly      
    toc: true
    page-layout: full
    css: style.css
    grid:
      body-width: 1200px
    fig-cap-location: margin
    reference-location: margin
    citation-location: margin
  pdf:
    geometry: margin=2.5cm
    documentclass: article
format-links: [pdf]

authors:
  - Sandro Vitenti
jupyter: python3
license: CC BY-NC-SA 4.0
